### ISSUE TITLE
why are you computing median values? 

### ISSUE THREAD

**Issue by jasan-s** [Esri/html5-geolocation-tool-js#29]
Was there a reason you are calculating median values?  You don't seem to use them in the app @ https://esri.github.io/html5-geolocation-tool-js/field-location-template.html

**Comment by andygup** [comment]
@jasan-s thanks for the question. 

Both average and median are included in the `GeolocationHelper.js` library to allow the you to decide which approach is best based on your requirements, use cases and equipment. My intent was to keep the template as simple as possible and allow you to tweak it based on unique needs. The challenge is that GPS satellite signals are constantly fluctuating and the causes the reported location to move around, even if you are standing still.

Average is often treated as the go-to approach, however it's best suited for fairly normal GPS location distributions. The gotcha is a single GPS value that is too high or too low can affect the average. The library tries to help minimize that somewhat by allowing you set to a `MAX_ACCURACY` property, but that doesn't eliminate the potential for all results to be affected by one spurious location value and/or due to differences between [accuracy and precision](http://www.mathsisfun.com/accuracy-precision.html). 

Median is often used for measuring skewed results and determining a central tendency. Median gives you the exact center. 

Here's an [interesting article](http://blog.skyhookwireless.com/advertising/the-difference-between-location-accuracy-and-precision-and-why-you-need-to-know) that touches on real-life uses cases of how accuracy and precision can affect actual versus perceived location.

To help illustrate the points above, here is a screenshot of a demonstration where I walked around a building from left to right. The left-most screenshot are the GPS location results using a Trimble R1 high-accuracy GPS bluetoothed to an Android phone. On the right is the Android phone by itself.  GPS locations are represented by the red dots.

![image](https://cloud.githubusercontent.com/assets/510440/19859325/7f63a88e-9f4a-11e6-913e-ef6c9c280b59.png)

**Comment by jasan-s** [comment]
Thanks for the detailed answer.  I suppose I will try both and see which results in better  user experience for my use case.  Although I think, limiting the accepted values with accuracy threshold may be enough for my use.

**Comment by jasan-s** [comment]
Followup question @andygup , It's my understanding that taking median and average of geolocation works better for walking or standing still users, in a moving car the averaging and median method would not be reliable.  would you agree?

**Comment by andygup** [comment]
@jasan-s The field location template app was specifically designed for helping to determine the best possible single location while standing still. 

And, yep, the game definitely changes when measuring location while moving. There are many academic and professional papers written on this topic, such as this [one](https://www.depts.ttu.edu/transtech/Paper/21.pdf), and there are also patents. Mathematically speaking, some sampling (average or median + standard deviation and other factors such as forward velocity) is better than using a single, raw geolocation. It's balance between sample size and performance.  

Another thing to keep in mind, app makers like Google Maps have access to vector-based road network information and can snap your location to the correct side of the road, or road segment or an intersection, for example.
